export class CotizacionesTextilModel {
    cotizacion_id: number = 0;
    tipo: number = 0;
    articulo: string = '';
    color: string = '';
    titulo_tela: string = '';
    ancho_total: string = '';
    densidad_aw: string = '';
    densidad_bw: string = '';
    proveedor: string = '';
    revirado: string = '';
    encogimiento_largo: string = '';
    encogimiento_ancho: string = '';
    precio: string = '';
    largo_tizado_a: string = '';
    tolerancia: string = '';
    componente: string = '';
    eficiencia: string = '';
    largo_tizado_b: string = '';
    consumo_neto: string = '';
    merma_corte: string = '';
    deleted_status: number = 0;
    created_at: string = '';
    updated_at: string = '';
    deleted_at: string = '';
}