export class CotizacionesModel {
    id: number = 0;
    cliente_id: number = 0;
    usuario_id: number = 0;
    temporada_id: number = 0;
    codigo: string = '';
    estilo: string = '';
    tipo_tela: string = '';
    composicion_tela: string = '';
    complemento1: string = '';
    complemento2: string = '';
    complemento3: string = '';
    complemento4: string = '';
    tp_archivo: string = '';
    hm_archivo: string = '';
    deleted_status: number = 0;
    created_at: string = '';
    updated_at: string = '';
    deleted_at: string = '';
}